export const customVitamins = [
  { key: "Category", val: "Category" },
  { key: "Nutrient Data Bank Number", val: "Nutrient Data Bank Number" },
  { key: "Alpha Carotene", val: "Alpha Carotene" },
  { key: "Beta Carotene", val: "Beta Carotene" },
  { key: "Beta Cryptoxanthin", val: "Beta Cryptoxanthin" },
  { key: "Carbohydrate", val: "Carbohydrate" },
  { key: "Cholesterol", val: "Cholesterol" },
  { key: "Choline", val: "Choline" },
  { key: "Fiber", val: "Fiber" },
  { key: "Lutein and Zeaxanthin", val: "Lutein and Zeaxanthin" },
  { key: "Lycopene", val: "Lycopene" },
  { key: "Niacin", val: "Niacin" },
  { key: "Protein", val: "Protein" },
  { key: "Retinol", val: "Retinol" },
  { key: "Riboflavin", val: "Riboflavin" },
  { key: "Selenium", val: "Selenium" },
  { key: "Sugar Total", val: "Sugar Total" },
  { key: "Thiamin", val: "Thiamin" },
  { key: "Water", val: "Water" },
  { key: "Fat.Monosaturated Fat", val: "Monosaturated Fat" },
  { key: "Fat.Polysaturated Fat", val: "Polysaturated Fat" },
  { key: "Fat.Saturated Fat", val: "Saturated Fat" },
  { key: "Fat.Total Lipid", val: "Total Lipid" },
  { key: "Major Minerals.Calcium", val: "Calcium" },
  { key: "Major Minerals.Copper", val: "Copper" },
  { key: "Major Minerals.Iron", val: "Iron" },
  { key: "Major Minerals.Magnesium", val: "Magnesium" },
  { key: "Major Minerals.Phosphorus", val: "Phosphorus" },
  { key: "Major Minerals.Potassium", val: "Potassium" },
  { key: "Major Minerals.Sodium", val: "Sodium" },
  { key: "Major Minerals.Zinc", val: "Zinc" },
  { key: "Vitamins.Vitamin A - RAE", val: "Vitamin A - RAE" },
  { key: "Vitamins.Vitamin B12", val: "Vitamin B12" },
  { key: "Vitamins.Vitamin B6", val: "Vitamin B6" },
  { key: "Vitamins.Vitamin C", val: "Vitamin C" },
  { key: "Vitamins.Vitamin E", val: "Vitamin E" },
  { key: "Vitamins.Vitamin K", val: "Vitamin K" },
];
